name = "skillswap"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "skillswap-db"
database_id = "062ebd16-d769-405a-a9a7-6b852202de9b"
